project_id = "gtuaxxlrmyeplnarfmqc"

[functions.categorize-script]
verify_jwt = false

[functions.create-videographer]
verify_jwt = false

[functions.reset-password-admin]
verify_jwt = false

[functions.fetch-leads]
verify_jwt = false

[functions.update-lead-status]
verify_jwt = false

[functions.sync-notion-script]
verify_jwt = false

[functions.bulk-sync-notion-scripts]
verify_jwt = false

[functions.get-subscription]
verify_jwt = false

[functions.ai-build-script]
verify_jwt = false
