import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Loader2, Play, CheckCircle2, AlertCircle, Clock, Mail, LogOut, Facebook, ChevronRight } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { followupEngine } from "@/services/followupEngine";
import { followupWorker } from "@/workers/followupWorker";
import type { Lead } from "@/services/leadService";

interface WorkflowStep {
  id: number;
  title: string;
  description: string;
  icon: any;
  timing: string;
  color: string;
  action: () => Promise<void>;
}

interface ExecutionLog {
  step: number;
  status: "running" | "success" | "error";
  message: string;
  timestamp: Date;
  duration?: number;
}

export default function FollowUpWorkflowBuilder({ clientId }: { clientId: string }) {
  const [showTestModal, setShowTestModal] = useState(false);
  const [showFacebookAuth, setShowFacebookAuth] = useState(false);

  // Test data
  const [testLead, setTestLead] = useState({
    name: "Test Lead",
    email: "test@example.com",
    phone: "+1234567890",
    source: "facebook",
  });

  const [testLeadId, setTestLeadId] = useState<string | null>(null);
  const [executionLogs, setExecutionLogs] = useState<ExecutionLog[]>([]);
  const [isRunning, setIsRunning] = useState(false);
  const [facebookConnected, setFacebookConnected] = useState(false);

  // Create test lead
  const createTestLead = async () => {
    try {
      setIsRunning(true);
      const { data, error } = await supabase.from("leads").insert([
        {
          client_id: clientId,
          name: testLead.name,
          email: testLead.email,
          phone: testLead.phone,
          source: testLead.source,
          status: "new",
          follow_up_step: 0,
          booked: false,
          stopped: false,
          replied: false,
        },
      ]).select().single();

      if (error) throw error;
      setTestLeadId(data.id);
      addLog(0, "success", `Test lead created: ${data.id}`);
      toast.success("Test lead created successfully");
      return data.id;
    } catch (error) {
      addLog(0, "error", `Failed to create test lead: ${error}`);
      toast.error("Failed to create test lead");
      return null;
    } finally {
      setIsRunning(false);
    }
  };

  // Step 1: Verify lead
  const verifyLead = async () => {
    if (!testLeadId) {
      toast.error("Create test lead first");
      return;
    }
    try {
      addLog(1, "running", "Verifying lead...");
      const { data, error } = await supabase.from("leads").select("*").eq("id", testLeadId).single();
      if (error) throw error;

      addLog(1, "success", `Lead verified: ${data.name} (${data.email})`);
      toast.success("Lead verified");
    } catch (error) {
      addLog(1, "error", String(error));
      toast.error("Lead verification failed");
    }
  };

  // Step 2: Generate message
  const generateMessage = async () => {
    if (!testLeadId) {
      toast.error("Create test lead first");
      return;
    }
    try {
      addLog(2, "running", "Generating message with Claude AI...");
      const { data: lead } = await supabase.from("leads").select("*").eq("id", testLeadId).single();

      if (!lead) throw new Error("Lead not found");

      // Import and call AI generator
      const { aiGenerator } = await import("@/services/aiGenerator");
      const message = await aiGenerator.generateFollowUpMessage(lead, 1);

      addLog(
        2,
        "success",
        `Message generated:\nSubject: ${message.subject}\nBody: ${message.body.substring(0, 100)}...`
      );
      toast.success("Message generated by Claude");
    } catch (error) {
      addLog(2, "error", String(error));
      toast.error("Message generation failed");
    }
  };

  // Step 3: Send email
  const sendEmail = async () => {
    if (!testLeadId) {
      toast.error("Create test lead first");
      return;
    }
    try {
      addLog(3, "running", "Sending email via Zoho...");
      const { data: lead } = await supabase.from("leads").select("*").eq("id", testLeadId).single();

      if (!lead || !lead.email) {
        throw new Error("Lead or email not found");
      }

      // In production, this would call a backend endpoint
      // For now, simulate sending
      const { messageService } = await import("@/services/messageService");
      const sendResult = await messageService.sendMessage({
        lead,
        channel: "email",
        subject: "Test Follow-up",
        body: "This is a test follow-up message",
        fromName: "Test Sender",
      });

      if (!sendResult.success) {
        throw new Error(sendResult.error || "Failed to send email");
      }

      addLog(3, "success", `Email sent to ${lead.email}`);
      toast.success("Email sent successfully");
    } catch (error) {
      addLog(3, "error", String(error));
      toast.error("Email sending failed");
    }
  };

  // Step 4: Log message
  const logMessage = async () => {
    if (!testLeadId) {
      toast.error("Create test lead first");
      return;
    }
    try {
      addLog(4, "running", "Logging message to database...");
      const { error } = await supabase.from("messages").insert([
        {
          lead_id: testLeadId,
          direction: "outbound",
          channel: "email",
          subject: "Test Follow-up",
          body: "This is a test follow-up message",
          sent_at: new Date().toISOString(),
        },
      ]);

      if (error) throw error;
      addLog(4, "success", "Message logged to messages table");
      toast.success("Message logged");
    } catch (error) {
      addLog(4, "error", String(error));
      toast.error("Message logging failed");
    }
  };

  // Step 5: Schedule next
  const scheduleNext = async () => {
    if (!testLeadId) {
      toast.error("Create test lead first");
      return;
    }
    try {
      addLog(5, "running", "Scheduling next follow-up...");
      const nextTime = new Date(Date.now() + 10 * 60000); // +10 minutes

      const { error } = await supabase
        .from("leads")
        .update({
          follow_up_step: 1,
          next_follow_up_at: nextTime.toISOString(),
          last_contacted_at: new Date().toISOString(),
        })
        .eq("id", testLeadId);

      if (error) throw error;
      addLog(
        5,
        "success",
        `Next follow-up scheduled for ${nextTime.toLocaleString()}`
      );
      toast.success("Next follow-up scheduled");
    } catch (error) {
      addLog(5, "error", String(error));
      toast.error("Scheduling failed");
    }
  };

  // Full automation test
  const runFullAutomation = async () => {
    try {
      setIsRunning(true);
      setExecutionLogs([]);

      // Create lead
      const leadId = await createTestLead();
      if (!leadId) return;

      // Run all steps
      await verifyLead();
      await new Promise((resolve) => setTimeout(resolve, 500));

      await generateMessage();
      await new Promise((resolve) => setTimeout(resolve, 500));

      await sendEmail();
      await new Promise((resolve) => setTimeout(resolve, 500));

      await logMessage();
      await new Promise((resolve) => setTimeout(resolve, 500));

      await scheduleNext();

      toast.success("Full workflow executed successfully!");
    } catch (error) {
      console.error("Workflow error:", error);
      toast.error("Workflow execution failed");
    } finally {
      setIsRunning(false);
    }
  };

  const addLog = (step: number, status: "running" | "success" | "error", message: string) => {
    setExecutionLogs((prev) => [
      ...prev,
      {
        step,
        status,
        message,
        timestamp: new Date(),
      },
    ]);
  };

  const steps = [
    {
      id: 1,
      title: "Lead Created",
      description: "New Facebook lead stored in database",
      icon: "📥",
      timing: "Immediate",
      color: "from-blue-500/20 to-blue-600/20",
    },
    {
      id: 2,
      title: "AI Message Generated",
      description: "Claude generates contextual follow-up text",
      icon: "🤖",
      timing: "Immediate",
      color: "from-purple-500/20 to-purple-600/20",
    },
    {
      id: 3,
      title: "Email Sent",
      description: "Message delivered via Zoho SMTP",
      icon: "✉️",
      timing: "Immediate",
      color: "from-green-500/20 to-green-600/20",
    },
    {
      id: 4,
      title: "Message Logged",
      description: "Communication stored in messages table",
      icon: "📝",
      timing: "Immediate",
      color: "from-yellow-500/20 to-yellow-600/20",
    },
    {
      id: 5,
      title: "Next Scheduled",
      description: "Follow-up scheduled based on sequence",
      icon: "⏰",
      timing: "+10min, +1day, +2days, +3days",
      color: "from-orange-500/20 to-orange-600/20",
    },
  ];

  return (
    <div className="space-y-6">
      {/* Header with Facebook Auth */}
      <div className="flex items-center justify-between">
        <h2 className="text-xl font-bold text-foreground">Live Workflow Test</h2>
        <Button
          variant={facebookConnected ? "default" : "outline"}
          onClick={() => setShowFacebookAuth(true)}
          className="gap-2"
        >
          <Facebook className="w-4 h-4" />
          {facebookConnected ? "✓ Facebook Connected" : "Connect Facebook"}
        </Button>
      </div>

      {/* Workflow Steps Visualization */}
      <div className="space-y-3">
        {steps.map((step, idx) => (
          <div key={step.id}>
            <div
              className={`bg-gradient-to-r ${step.color} border border-border/30 rounded-lg p-4 flex items-start justify-between hover:border-border/50 transition`}
            >
              <div className="flex items-start gap-4 flex-1">
                <div className="text-2xl">{step.icon}</div>
                <div className="flex-1">
                  <h3 className="font-semibold text-foreground">{step.title}</h3>
                  <p className="text-xs text-muted-foreground mt-1">{step.description}</p>
                  <p className="text-xs text-muted-foreground mt-2">⏱️ {step.timing}</p>
                </div>
              </div>
              <Button
                size="sm"
                variant="ghost"
                onClick={async () => {
                  setTestLeadId(null);
                  setExecutionLogs([]);
                  setShowTestModal(true);
                }}
                className="gap-1"
              >
                <Play className="w-4 h-4" />
                Test
              </Button>
            </div>
            {idx < steps.length - 1 && (
              <div className="flex justify-center py-2">
                <ChevronRight className="w-5 h-5 text-muted-foreground/50 rotate-90" />
              </div>
            )}
          </div>
        ))}
      </div>

      {/* Control Buttons */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        <Button
          onClick={() => setShowTestModal(true)}
          disabled={isRunning}
          className="gap-2"
          variant="outline"
        >
          <Play className="w-4 h-4" />
          {isRunning ? "Running..." : "Test Workflow"}
        </Button>
        <Button
          onClick={runFullAutomation}
          disabled={isRunning}
          className="gap-2"
        >
          {isRunning && <Loader2 className="w-4 h-4 animate-spin" />}
          {isRunning ? "Executing..." : "Run Full Automation"}
        </Button>
      </div>

      {/* Execution Logs */}
      {executionLogs.length > 0 && (
        <div className="bg-background/50 border border-border/30 rounded-lg p-4 space-y-2 max-h-64 overflow-y-auto">
          <h3 className="font-semibold text-foreground text-sm mb-3">Execution Log</h3>
          {executionLogs.map((log, idx) => (
            <div
              key={idx}
              className={`p-2 rounded text-xs font-mono border-l-2 ${
                log.status === "success"
                  ? "bg-green-500/10 border-green-500 text-green-200"
                  : log.status === "error"
                    ? "bg-red-500/10 border-red-500 text-red-200"
                    : "bg-blue-500/10 border-blue-500 text-blue-200"
              }`}
            >
              <div className="flex items-start gap-2">
                {log.status === "success" && <CheckCircle2 className="w-3 h-3 mt-0.5 flex-shrink-0" />}
                {log.status === "error" && <AlertCircle className="w-3 h-3 mt-0.5 flex-shrink-0" />}
                {log.status === "running" && <Loader2 className="w-3 h-3 mt-0.5 flex-shrink-0 animate-spin" />}
                <div>
                  <p className="font-semibold">Step {log.step}: {log.status.toUpperCase()}</p>
                  <p className="mt-1 whitespace-pre-wrap">{log.message}</p>
                  <p className="text-xs opacity-70 mt-1">{log.timestamp.toLocaleTimeString()}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Test Modal */}
      <Dialog open={showTestModal} onOpenChange={setShowTestModal}>
        <DialogContent className="sm:max-w-md max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Test Lead Data</DialogTitle>
          </DialogHeader>

          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <label className="text-sm font-medium">Lead Name</label>
              <Input
                placeholder="John Doe"
                value={testLead.name}
                onChange={(e) => setTestLead({ ...testLead, name: e.target.value })}
              />
            </div>

            <div className="space-y-2">
              <label className="text-sm font-medium">Email</label>
              <Input
                type="email"
                placeholder="john@example.com"
                value={testLead.email}
                onChange={(e) => setTestLead({ ...testLead, email: e.target.value })}
              />
            </div>

            <div className="space-y-2">
              <label className="text-sm font-medium">Phone</label>
              <Input
                placeholder="+1234567890"
                value={testLead.phone}
                onChange={(e) => setTestLead({ ...testLead, phone: e.target.value })}
              />
            </div>

            <div className="space-y-2">
              <label className="text-sm font-medium">Source</label>
              <Input
                placeholder="facebook"
                value={testLead.source}
                onChange={(e) => setTestLead({ ...testLead, source: e.target.value })}
              />
            </div>

            {testLeadId && (
              <div className="p-3 bg-green-500/10 border border-green-500/30 rounded text-xs text-green-200">
                ✓ Test lead created: {testLeadId}
              </div>
            )}

            {executionLogs.length > 0 && (
              <div className="max-h-48 overflow-y-auto space-y-2 p-2 bg-background rounded border border-border/30">
                {executionLogs.map((log, idx) => (
                  <div key={idx} className="text-xs">
                    <span className={log.status === "success" ? "text-green-400" : "text-yellow-400"}>
                      [{log.status}]
                    </span>{" "}
                    Step {log.step}: {log.message.substring(0, 50)}...
                  </div>
                ))}
              </div>
            )}
          </div>

          <DialogFooter className="flex gap-2">
            <Button
              variant="outline"
              onClick={() => {
                setShowTestModal(false);
                setExecutionLogs([]);
              }}
            >
              Close
            </Button>
            <Button
              onClick={runFullAutomation}
              disabled={isRunning}
              className="gap-2"
            >
              {isRunning && <Loader2 className="w-4 h-4 animate-spin" />}
              {testLeadId ? "Run Next Step" : "Create & Run"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Facebook Auth Modal */}
      <Dialog open={showFacebookAuth} onOpenChange={setShowFacebookAuth}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Connect Facebook Account</DialogTitle>
          </DialogHeader>

          <div className="space-y-4 py-4">
            <p className="text-sm text-muted-foreground">
              Connect your Facebook account to automatically receive leads from Facebook Lead Forms.
            </p>

            <div className="space-y-2 p-4 bg-background/50 rounded border border-border/30">
              <h4 className="font-semibold text-sm">Steps:</h4>
              <ol className="text-xs space-y-1 text-muted-foreground">
                <li>1. Click "Connect Facebook" button below</li>
                <li>2. Authorize the app to access your Facebook Pages</li>
                <li>3. Select the Page with Lead Forms</li>
                <li>4. Configure Lead Form webhook</li>
              </ol>
            </div>

            <div className="p-3 bg-blue-500/10 border border-blue-500/30 rounded text-xs text-blue-200">
              📌 Your leads will be automatically received and follow-ups will start immediately.
            </div>
          </div>

          <DialogFooter className="flex gap-2">
            <Button variant="outline" onClick={() => setShowFacebookAuth(false)}>
              Cancel
            </Button>
            <Button
              onClick={() => {
                setFacebookConnected(true);
                setShowFacebookAuth(false);
                toast.success("Facebook connected (simulated)");
              }}
              className="gap-2"
            >
              <Facebook className="w-4 h-4" />
              Connect Facebook
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
